# Generated by Django 4.1.4 on 2022-12-06 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beeLine_Request_Number', models.CharField(max_length=30)),
                ('job_description', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=100)),
                ('no_of_positions', models.IntegerField()),
                ('priority', models.CharField(max_length=30)),
                ('cv_DeadLine', models.DateField()),
                ('billing_Rate', models.CharField(max_length=100)),
                ('hours_per_week', models.IntegerField()),
                ('contact_person', models.CharField(max_length=30)),
                ('date_request', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_Status', models.CharField(max_length=100)),
                ('name_of_candidate', models.CharField(max_length=100)),
                ('next_step', models.CharField(max_length=200)),
                ('dutch_Language', models.CharField(max_length=5)),
                ('location_relocation', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('resume_Shared', models.CharField(max_length=5)),
                ('client_Interview', models.CharField(max_length=5)),
                ('comments', models.CharField(default=False, max_length=1000)),
                ('beeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beeline', to='book.beeline')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
