# Generated by Django 4.1.4 on 2022-12-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_beeline_profile_remove_book_author_delete_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prodapt_POC',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='prodapt_practice',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
