# Generated by Django 4.1.4 on 2022-12-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_beeline_jd_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beeline',
            old_name='jd_upload',
            new_name='name',
        ),
    ]
