# Generated by Django 4.1.4 on 2022-12-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_beeline_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(default=False, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='beeline',
            name='name',
        ),
    ]
