# Generated by Django 4.1.4 on 2022-12-19 12:28

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_upload_remove_beeline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='name',
            field=models.FileField(blank=True, null=True, upload_to=book.models.upload_path),
        ),
    ]
