# Generated by Django 4.1.4 on 2022-12-19 12:49

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_upload_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AddField(
            model_name='beeline',
            name='name',
            field=models.FileField(blank=True, null=True, upload_to=book.models.upload_path),
        ),
    ]
