# Generated by Django 4.1.4 on 2022-12-19 13:31

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_delete_upload_beeline_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(blank=True, null=True, upload_to=book.models.upload_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='beeline',
            name='name',
        ),
    ]
