# Generated by Django 4.1.4 on 2022-12-20 07:17

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_upload_remove_beeline_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AddField(
            model_name='beeline',
            name='name',
            field=models.FileField(blank=True, null=True, upload_to=book.models.upload_path),
        ),
    ]
