# Generated by Django 4.1.4 on 2022-12-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_delete_upload_beeline_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beeline',
            old_name='name',
            new_name='file',
        ),
    ]
