# Generated by Django 4.1.4 on 2022-12-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_profile_cv_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resume_Shared',
        ),
    ]
