# Generated by Django 4.1.4 on 2023-01-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_remove_profile_resume_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeline',
            name='beeline_Status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
