# Generated by Django 4.1.4 on 2023-01-04 07:19

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_beeline_beeline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beeline',
            name='file',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/anonymous.jpg', null=True, upload_to=book.models.upload_path),
        ),
    ]
