# Generated by Django 4.1.4 on 2023-01-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_alter_beeline_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beeline',
            old_name='beeline_Status',
            new_name='status',
        ),
    ]
